import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CooperBlack } from "./font";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import SmoothScroll from "@/components/layout/container/SmoothScroll";
import { Suspense } from "react";
import Fallback from "@/components/common/fallback/Fallback";
import ReduxProvider from "@/store/provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Hibachef",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${CooperBlack.variable}  antialiased`}>
        <Suspense fallback={<Fallback />}>
          <ReduxProvider>
            <SmoothScroll>
              <Header />
              <div className="min-h-[calc(100dvh-338px)] md:min-h-[calc(100dvh-360px)] bg-background">
                {children}
              </div>
              <Footer />
            </SmoothScroll>
          </ReduxProvider>
        </Suspense>
      </body>
    </html>
  );
}
